name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run tests
      run: mvn clean test

    - name: Test Summary
      if: always()
      run: |
        echo "### Test Results 🧪" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        mvn surefire-report:report-only > /dev/null 2>&1 || true
        if [ -f target/surefire-reports/TEST-*.xml ]; then
          echo "✅ Tests completed successfully" >> $GITHUB_STEP_SUMMARY
        fi
